<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Mapping\**" />
    <Compile Remove="Validators\**" />
    <EmbeddedResource Remove="Mapping\**" />
    <EmbeddedResource Remove="Validators\**" />
    <None Remove="Mapping\**" />
    <None Remove="Validators\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Models\" />
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Responses\" />
    <Folder Include="Contracts\Infrastructure\" />
    <Folder Include="Features\Auth\Mapping\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartHealthcare.Domain\SmartHealthcare.Domain.csproj" />
  </ItemGroup>

</Project>
